In [1]:
# packages
import numpy as np
import pandas as pd

In [2]:
# hide warning messages
import warnings
warnings.filterwarnings("ignore")

In [20]:
path = '../../../input/returns/rosettaupdated.parquet'
rosettaupdated = pd.read_parquet(path)

In [78]:
rosettaupdated

,PERMNO,date,COMNAM,TAQ_TICKER,RET,MARKETCAP
0,10001,2003-01-02,ENERGY WEST INC,EWST,0.088287,2.072800e+04
1,10001,2003-01-03,ENERGY WEST INC,EWST,0.052500,2.181622e+04
2,10001,2003-01-06,ENERGY WEST INC,EWST,-0.019121,2.139907e+04
3,10001,2003-01-07,ENERGY WEST INC,EWST,0.004964,2.150530e+04
4,10001,2003-01-08,ENERGY WEST INC,EWST,0.006024,2.163485e+04
...,...,...,...,...,...,...
18884619,93436,2020-12-24,TESLA INC,TSLA,0.024444,6.272925e+08
18884620,93436,2020-12-28,TESLA INC,TSLA,0.002901,6.291124e+08
18884621,93436,2020-12-29,TESLA INC,TSLA,0.003465,6.312926e+08
18884622,93436,2020-12-30,TESLA INC,TSLA,0.043229,6.585827e+08
18884623,93436,2020-12-31,TESLA INC,TSLA,0.015674,6.689053e+08

data_treatment function: receives two parameters, ticker.

* ticker is the firm TAQ ticker which will treat.

This funtion returns the dataframe treated with onlye date (index) and returns of this company.

In [55]:
def data_treatment(ticker):
    # getting just the data for this ticker
    df_ticker = rosettaupdated[rosettaupdated['TAQ_TICKER'] == ticker]
    
    # renaming the return column to the ticker name
    df_ticker = df_ticker.rename({'RET': ticker}, axis=1)

    # setting date as index
    df_ticker = df_ticker.set_index('date')

    # keeping just the returns column
    df_ticker = df_ticker[[ticker]]

    # return the dataframe treated
    return(df_ticker)

In [57]:
daterange = rosettaupdated['date'].unique()
df = pd.DataFrame(index=daterange)

In [58]:
tickers = rosettaupdated['TAQ_TICKER'].unique()

In [216]:
for ticker in tickers[7879:]:
    # data_treatment function
    df_ticker = data_treatment(ticker)

    # concatenating the ticker firm returns to the main dataframe
    df = pd.concat([df, df_ticker], axis=1)

In [229]:
df

,EWST,EWSTE,EWSTD,EGAS,BTFG,DPAC,AEPI,JJSF,DGSE,DGC,...,BSFT,CBOE,CYDE,JGBO,MOTR,VLTC,SANW,SCEI,TSLA,CBCL
2003-01-02,0.088287,NaN,NaN,NaN,-0.008559,0.051449,-0.005356,-0.013722,0.023474,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.014698
2003-01-03,0.052500,NaN,NaN,NaN,0.008632,0.068229,0.026923,0.005111,-0.004587,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.034953
2003-01-06,-0.019121,NaN,NaN,NaN,-0.009009,0.045161,0.037453,0.005367,-0.078341,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.004080
2003-01-07,0.004964,NaN,NaN,NaN,0.000455,-0.021605,-0.043321,-0.026946,0.050000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.017156
2003-01-08,0.006024,NaN,NaN,NaN,0.000000,-0.028391,-0.031698,0.061188,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.038171
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.001727,NaN,NaN,...,NaN,0.010428,NaN,NaN,NaN,NaN,0.019544,NaN,0.024444,NaN
2020-12-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.002618,NaN,NaN,...,NaN,0.013580,NaN,NaN,NaN,NaN,-0.041534,NaN,0.002901,NaN
2020-12-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.013637,NaN,NaN,...,NaN,-0.017578,NaN,NaN,NaN,NaN,-0.038333,NaN,0.003465,NaN
2020-12-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000584,NaN,NaN,...,NaN,0.010473,NaN,NaN,NaN,NaN,-0.001733,NaN,0.043229,NaN
2020-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.007914,NaN,NaN,...,NaN,0.005398,NaN,NaN,NaN,NaN,0.017361,NaN,0.015674,NaN

In [230]:
path = '../../../input/returns/daily_rosetta.parquet'
df.to_parquet(path)